name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true 
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
   
    - name: install pandoc
      run: |
        sudo apt-get install -y pandoc
    
    # Deploy hexo blog website.
    - name: Set git environment
      env: 
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        USERNAME: hyiker
        EMAIL: 961531608@qq.com
      run: |
        mkdir -p ~/.ssh/
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name "$USERNAME"
        git config --global user.email "$EMAIL"
    - name: Setup Hexo environment
      run: |
        npm install -g hexo-cli
        npm install
    - name: Deploy Hexo
      run: |
        hexo g
        hexo d